/**
 * Types and loading for the hero interaction timeline.
 *
 * `public/hero/timeline.json` is generated by `scripts/build-hero-assets.mjs`
 * from the owner-supplied frame archives. It is derived data, never hand-edited.
 */

export interface PanelDef {
  id: string;
  label: string;
  href: string;
}

/** Per-frame interaction state for the panel sequence. */
export interface PanelState {
  /** Index into `HeroTimeline.panels`. */
  p: number;
  /** Normalised [x, y, width, height] of the visible panel, 0..1. */
  box: [number, number, number, number];
  /** 1 when the panel is settled enough to be a click target. */
  c: 0 | 1;
}

export interface HeroTimeline {
  source: { width: number; height: number };
  decimate: number;
  tiers: string[];
  panels: PanelDef[];
  sequences: {
    seq1: { frames: number };
    seq2: { frames: number; states: (PanelState | null)[] };
    seq3: { frames: number };
  };
}

/**
 * Scroll-progress bands for the hero.
 *
 * The sequence follows prompt §8–§12:
 *   seq1   "Have an Idea?" holds, then the card slides up like a webpage to
 *          reveal the workstation. That transition is already in the supplied
 *          frames, so it is scrubbed rather than recreated.
 *   seq2   the six service panels, each emerging, settling and retracting with
 *          zero overlap. Clickable throughout its settled frames.
 *   brand  GENRA + BUILD. AUTOMATE. ADVANCE. — built in DOM because the owner
 *          supplied no frames for this beat, and §12 asks for the real brand
 *          identity rather than another animation frame.
 *   seq3   "You name it. / We build it." closing card, from supplied frames.
 *
 * Stage changes translate upward like a page scroll — no zoom, no fade to
 * black, no particles (§8).
 */
export const BANDS = {
  seq1: [0, 0.14],
  seq2: [0.14, 0.62],
  liftToBrand: [0.62, 0.7],
  brand: [0.7, 0.8],
  liftToClosing: [0.8, 0.86],
  seq3: [0.86, 1],
} as const;

/** Total scroll distance allotted to the pinned hero, in viewport heights. */
export const HERO_SCROLL_VH = 600;

/** Map a global progress value into 0..1 within a band. */
export function bandProgress(
  progress: number,
  band: readonly [number, number],
): number {
  const [start, end] = band;
  if (progress <= start) return 0;
  if (progress >= end) return 1;
  return (progress - start) / (end - start);
}

/** Pick the width tier for a viewport. Mirrors the tiers the build emits. */
export function tierFor(width: number): string {
  if (width <= 700) return "sm";
  if (width <= 1400) return "md";
  return "lg";
}

export async function loadTimeline(signal?: AbortSignal): Promise<HeroTimeline> {
  const res = await fetch("/hero/timeline.json", { signal });
  if (!res.ok) throw new Error(`hero timeline unavailable (${res.status})`);
  return res.json();
}
